# Generated by Django 2.1.5 on 2019-02-01 01:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('htmlpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlpage',
            name='body',
            field=wagtail.core.fields.StreamField([('page_content', wagtail.core.blocks.RawHTMLBlock(required=True))], blank=True, null=True),
        ),
    ]
