# Generated by Django 2.1.5 on 2019-01-08 14:37

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190108_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.StructBlock([('padding_top', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'None'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')])), ('padding_bottom', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'None'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')])), ('heading', wagtail.core.blocks.CharBlock(classname='full title'))])), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('three_column_blocks', wagtail.core.blocks.StructBlock([('padding_top', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'None'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')])), ('padding_bottom', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'None'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')])), ('heading_1', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph_1', wagtail.core.blocks.RichTextBlock()), ('heading_2', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph_2', wagtail.core.blocks.RichTextBlock()), ('heading_3', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph_3', wagtail.core.blocks.RichTextBlock())])), ('button_block', wagtail.core.blocks.StructBlock([('padding_top', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'None'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')])), ('padding_bottom', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'None'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')])), ('text', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.CharBlock())])), ('gird_column_block_collection', wagtail.core.blocks.StructBlock([('padding_top', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'None'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')])), ('padding_bottom', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'None'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')]))]))], blank=True, null=True),
        ),
    ]
